# COLORS

colorPrimary = "#000000"
colorSecondary = "#D9D9D9"
colorSurface = "#F3F7FF"
colorWhite = "#FFFFFF"
colorBlack = "#000000"
colorRed = "#F15857"
colorGreen = "#4FC449"

# STYLING ATTRIBUTES

# container used for register and login forms
containerFormWidth = "600px"

# container used for main layout
containerContentWidth = "1024px"


notifyMessagePosition = "top"

# LOCAL URLS

urlBaseBackend = "https://klub-zmj-test.dopracenakole.net"

# EXTERNAL URLS

urlAutoMat = "https://auto-mat.cz"
urlFreeSoftwareDefinition = "https://www.gnu.org/philosophy/free-sw.en.html"
urlInstagram = "https://www.instagram.com/spolekautomat"
urlAppDataPrivacyPolicy = "https://auto-mat.cz/zasady"
urlAppDataCodex = "https://zazitmestojinak.cz/kodex-zazit-mesto-jinak"
urlTwitter = "https://twitter.com/spolekautomat"
urlYoutube = "https://www.youtube.com/@spolekautomat"
urlZMJManual = "https://www.manual.zazitmestojinak.cz/"
urlDonate = "https://auto-mat.cz/nakrmte-automat"

# Event details

eventDate = "28.09.2026"
documentMaxFileUploadSizeMegabytes = 2
imageMaxFileUploadSizeMegabytes = 2


# API CONFIGURATION

# apiBase = "https://klub-zmj-test.dopracenakole.net/api/"
apiBase = "http://localhost:8000/api/"

apiDefaultLang = "cs"

urlApiHasUserVerifiedEmail = "auth/registration/has-user-verified-email-address/"
urlApiLogin = "auth/login/"
urlApiRefresh = "auth/token/refresh/"
urlApiRegister = "auth/registration/"
urlApiResendEmail = "auth/registration/send-confirmation-email/"
urlApiConfirmEmail = "auth/registration/account-confirm-email/"
urlApiResetPassword = "auth/password/reset/"
urlApiResetPasswordConfirm = "auth/password/reset/confirm/"

urlApiUser = "zmj/user/"
urlApiRegisterComplete = "zmj/registration/"
urlApiCheckRegistrationStatus = "zmj/registration/status/"
urlApiCompanyTypes = "zmj/company-types/"
urlApiEventCategories = "zmj/categories/"
urlApiEvents = "zmj/events/"
urlApiEventList = "zmj/events/"
urlApiEventInformation = "zmj/events/"
urlApiEventOrganizerCompany = "/company/"
urlApiEventOrganizers = "/organizers/"
urlApiEventContent = "/content/"
urlApiEventProgram = "/program/"
urlApiEventAgreement = "/agreement/"
urlApiEventInvoice = "/invoice/"
urlApiEventChecklist = "/checklist/"
urlApiEventContentPublic = "/public-on-web/"

checkIsEmailVerifiedInterval = 20 # seconds

# DATE TIME FORMATS

dateFormat = "DD.MM.YYYY"

dateTimeFormatsAllLocales = '''
{
  "numeric": {
    "year": "numeric",
    "month": "numeric",
    "day": "numeric"
  },
  "monthYear": {
    "year": "numeric",
    "month": "long"
  },
  "monthDay": {
    "month": "numeric",
    "day": "numeric"
  },
  "monthDayHourMinute" : {
    "month": "numeric",
    "day": "numeric",
    "hour": "numeric",
    "minute": "numeric"
  },
  "weekday": {
    "weekday": "long"
  },
  "monthLongStringDay": {
    "day": "numeric",
    "month": "long"
  }
}
'''

# NUMBER FORMATS

numberFormatsAllLocales = '''
{
  "routeDistanceDecimalNumber": {
    "style": "decimal",
    "minimumFractionDigits": 2,
    "maximumFractionDigits": 2,
    "roundingMode": "floor"
  }
}
'''

# SECRETS

secretString = "SECRET"

# MAP SETTINGS

mapCenterLon = "14.4378"
mapCenterLat = "50.0755"
